### PR TITLE
Fix leaking temp files

### PR DESCRIPTION
**Pull request by fritsduus**
Hi Mads
I had a lot of image files to compress and got an error because I ran out of available temp filenames. This Pull Request fixed the problem for me.
Regards
Frits

### CODE REVIEW

**Comment by madskristensen** [comment]
I think you missed a semicolon, so the PR doesn't compile

**Comment by fritsduus** [comment]
Yes, sorry its fixed now. Í am missing a project template and also the "$(VSToolsPath)\VSSDK\Microsoft.VsSDK.targets", so I had to hack the project file to make it build on my PC and then be careful not to commit these hacks.

**Comment by fritsduus** [comment]
Hmmm... looking over my commits again. We could also just go with my first commit. It is simpler and will perform better. Would you like me to change it back to that solution ?

**Comment by madskristensen** [comment]
Yeah, maybe close this PR and send a new one with the changes you want in?

**Pull request closed without merging**
