### PR TITLE
Added Google guetzli for lossless jpeg compression. resolve#32

### PR DESCRIPTION
**Pull request by al1b**
For get benefit of using guetzli, guetzli_windows_x86-64 added to project resources. ImageCompressor wll now use guetzli instead of jpegtran.

In my competitive test, I used all photos inside Artifact folder and here is the result:

| Tables        | Total size after compression|
| ------------- |:-------------:|
| jpegtran     | ~338 KB |
| **Google guetzli**     | **~300$ KB**      |

I have to change of the unit test methods to pass the test, and I think I made a mistake about it.

```
        [TestMethod, TestCategory("JPG")]
        public void Jpg_LossLess()
        {
            long savings = ExecuteTest("*.jpg", false);

            Assert.IsTrue(savings > 104895, "Don't compress enough");
        }
```

### CODE REVIEW

**Comment by madskristensen** [comment]
Thanks

**Comment by madskristensen** [comment]
Wow, Guetzli is super slow. It takes minutes to compress a few .jpg files. I'm not sure this should be on by default

**Comment by al1b** [comment]
> Thanks

You're welcome.

> Wow, Guetzli is super slow. It takes minutes to compress a few .jpg files. I'm not sure this should be on by default

Yes, I agree. It's slow and it should not be on by default. I'm afraid I forgot to mention it in the pull request. Do you think we could create a setting dialog for the extension? If you say so, I would implement it.

**Comment by madskristensen** [comment]
A setting would be the easiest, but I have another idea for changing the context menu structure that would then allow the user to explicitly run Guetzli

**Comment by al1b** [comment]
Seems nice to me too! I agree with that.

**Comment by al1b** [comment]
For example a context-menu structure like below?
*if the file is jpeg:*
```
Lossless  Image Image
-- Default Optimizer
-- Google Guetzli ( Lower output size, slow )

Lossy Optimize Image
-- Default Optmizer
-- Google Guetzli ( Lower output size, slow )
```

**Pull request merged**
