### PR TITLE
Modernize ImageOptimizer and add Visual Studio 2022 support

### PR DESCRIPTION
**Pull request by javierdlg**
This PR does the following:
- Modernizes the ImageOptimizer VSIX project with the latest SDK package and removes old references
- Migrates the source code to a shared project
- Adds a Dev17 VSIX project for Dev17 support

### CODE REVIEW

**Comment by madskristensen** [comment]
@javierdlg Looks like it couldn't find some packages in the CI build

**Comment by madskristensen** [comment]
@javierdlg 

> Could not load file or assembly 'Microsoft.VisualStudio.Interop, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03

**Comment by javierdlg** [comment]
@madskristensen that assembly should be getting pulled by the new SDK. I can build locally even after purging my nuget packages so it might be specific to AppVeyor. Do you have any specific settings that would prevent prerelease packages from being pulled as dependencies or something like that?

**Comment by madskristensen** [comment]
@javierdlg can we set up 30 minutes to go over the changes? I want to learn from what you did so I can write a blog post about it

**Comment by madskristensen** [comment]
It already supports VS 2022 and uploaded to the Marketplace https://marketplace.visualstudio.com/items?itemName=MadsKristensen.ImageOptimizer

No code changes were needed, so I don't think we should pursue this PR any longer. What do you think?

**Comment by tommck** [comment]
So.. you're using this PR as a demonstration on how to do things correctly from here: https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/samples?view=vs-2022

And yet the code is not "prod" code... That doesn't seem like the best documentation

**Comment by madskristensen** [comment]
Image Optimizer supports VS 2022

**Comment by tommck** [comment]
I just realized my comment sounded really whiny :)  Sorry for that.

**Pull request closed without merging**
